PressYourLuck/Controllers/PlayerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PressYourLuck.Helpers;
using PressYourLuck.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace PressYourLuck.Controllers
{
    public class PlayerController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Player player)
        {
            //if form is valid save the cookies for name and coin, and save it to session,then send it to database 
            if(ModelState.IsValid)
            {
                HttpContext.Response.Cookies.Append("Player-name", player.Name);
                HttpContext.Response.Cookies.Append("total-coins", player.TotalCoins.ToString());
                var audit = new Audit();
                audit.PlayerName = player.Name;
                audit.Amount = player.TotalCoins;
                audit.CreatedDate = DateTime.Now;
                audit.AuditTypeId = "A";
                HttpContext.Session.SetString("auditCashIn", JsonConvert.SerializeObject(audit));
                return RedirectToAction("Index", "Audit");
            }
            else
            {
                return View(player);
            }
        }
        public IActionResult CashOut()
        {
            //if cookie for player is not empty save the assign the cookie to audit list and save it to session then delete
            //cookie for name and total coin then send it to database. then display temp message for totalcoin
            if (Request.Cookies["Player-name"] != null)
            {
                var audit = new Audit();
                audit.PlayerName = HttpContext.Request.Cookies["player-name"];
                audit.Amount = CoinsHelper.GetTotalCoins(Request);
                audit.CreatedDate = DateTime.Now;
                audit.AuditTypeId = "B";
                HttpContext.Session.SetString("auditCashOut", JsonConvert.SerializeObject(audit));
                Response.Cookies.Delete("Player-name");
                Response.Cookies.Delete("total-coins");
            }
            TempData["message"] = $"You cashed out for {CoinsHelper.GetTotalCoins(Request)} coins";
            return RedirectToAction("Index", "Audit");
        }
    }
}

PressYourLuck/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Press Your Luck</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Press Your Luck</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Audit" asp-action="Index">Audit</a>
                        </li>
                    </ul>
                </div>

                @if (!string.IsNullOrEmpty(Context.Request.Cookies["player-name"]))
                {
                    <div>
                        Total Coins:@CoinsHelper.GetTotalCoins(Context.Request).ToString("c")
                        <a class="btn btn-success" asp-action="CashOut" asp-controller="Player" class="nav-link">Cash Out</a>
                    </div>
                }



            </div>
        </nav>
    </header>
    @if (TempData.Keys.Contains("message"))
    {
        <div class="alert alert-success alert-dismissible">
            <button class="close" data-dismiss="alert">&times;</button>
            @TempData["message"]
        </div>
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PressYourLuck
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>